const { db } = require('./src/config/firebase');

// Helper: tạo ngày HSD từ hôm nay + số ngày
function addDays(days) {
    const d = new Date();
    d.setDate(d.getDate() + days);
    return d.toISOString().split('T')[0]; // yyyy-mm-dd
}

const products = [
    {
        code: 'SP0001',
        name: 'Coca-Cola lon 330ml',
        category: 'Nước giải khát',
        unit: 'lon',
        importPrice: 7000,
        sellPrice: 10000,
        discountPrice: null,
        expiryDate: addDays(180),
        stockQuantity: 120,
        minStockThreshold: 20,
    },
    {
        code: 'SP0002',
        name: 'Pepsi lon 330ml',
        category: 'Nước giải khát',
        unit: 'lon',
        importPrice: 6800,
        sellPrice: 10000,
        discountPrice: 9000,
        expiryDate: addDays(150),
        stockQuantity: 90,
        minStockThreshold: 20,
    },
    {
        code: 'SP0003',
        name: 'Trà xanh Không Độ 500ml',
        category: 'Nước giải khát',
        unit: 'chai',
        importPrice: 8000,
        sellPrice: 12000,
        discountPrice: null,
        expiryDate: addDays(200),
        stockQuantity: 60,
        minStockThreshold: 15,
    },
    {
        code: 'SP0004',
        name: 'Sữa tươi Vinamilk có đường 220ml',
        category: 'Sữa & sản phẩm từ sữa',
        unit: 'hộp',
        importPrice: 5500,
        sellPrice: 8000,
        discountPrice: null,
        expiryDate: addDays(10),
        stockQuantity: 200,
        minStockThreshold: 30,
    },
    {
        code: 'SP0005',
        name: 'Sữa chua uống Yakult 5 chai',
        category: 'Sữa & sản phẩm từ sữa',
        unit: 'lốc',
        importPrice: 18000,
        sellPrice: 25000,
        discountPrice: 22000,
        expiryDate: addDays(20),
        stockQuantity: 40,
        minStockThreshold: 10,
    },
    {
        code: 'SP0006',
        name: 'Mì gói Hảo Hảo tôm chua cay',
        category: 'Thực phẩm khô',
        unit: 'gói',
        importPrice: 3500,
        sellPrice: 5000,
        discountPrice: null,
        expiryDate: addDays(300),
        stockQuantity: 500,
        minStockThreshold: 50,
    },
    {
        code: 'SP0007',
        name: 'Mì ly Omachi xốt bò hầm',
        category: 'Thực phẩm khô',
        unit: 'ly',
        importPrice: 9000,
        sellPrice: 13000,
        discountPrice: null,
        expiryDate: addDays(280),
        stockQuantity: 150,
        minStockThreshold: 30,
    },
    {
        code: 'SP0008',
        name: 'Bánh quy Cosy bơ sữa 270g',
        category: 'Bánh kẹo',
        unit: 'gói',
        importPrice: 15000,
        sellPrice: 21000,
        discountPrice: 18000,
        expiryDate: addDays(150),
        stockQuantity: 70,
        minStockThreshold: 15,
    },
    {
        code: 'SP0009',
        name: 'Kẹo dẻo Haribo 80g',
        category: 'Bánh kẹo',
        unit: 'gói',
        importPrice: 18000,
        sellPrice: 26000,
        discountPrice: null,
        expiryDate: addDays(365),
        stockQuantity: 45,
        minStockThreshold: 10,
    },
    {
        code: 'SP0010',
        name: 'Snack khoai tây Lay\'s vị muối',
        category: 'Bánh kẹo',
        unit: 'gói',
        importPrice: 9000,
        sellPrice: 13000,
        discountPrice: null,
        expiryDate: addDays(120),
        stockQuantity: 80,
        minStockThreshold: 20,
    },
    {
        code: 'SP0011',
        name: 'Nước suối Aquafina 500ml',
        category: 'Nước giải khát',
        unit: 'chai',
        importPrice: 3500,
        sellPrice: 6000,
        discountPrice: null,
        expiryDate: addDays(365),
        stockQuantity: 300,
        minStockThreshold: 50,
    },
    {
        code: 'SP0012',
        name: 'Cà phê sữa đá Nescafé lon 180ml',
        category: 'Nước giải khát',
        unit: 'lon',
        importPrice: 9500,
        sellPrice: 14000,
        discountPrice: 12000,
        expiryDate: addDays(200),
        stockQuantity: 55,
        minStockThreshold: 15,
    },
    {
        code: 'SP0013',
        name: 'Xúc xích Đức Việt 200g',
        category: 'Thực phẩm chế biến',
        unit: 'gói',
        importPrice: 22000,
        sellPrice: 30000,
        discountPrice: null,
        expiryDate: addDays(15),
        stockQuantity: 35,
        minStockThreshold: 10,
    },
    {
        code: 'SP0014',
        name: 'Trứng gà ta hộp 10 quả',
        category: 'Thực phẩm tươi sống',
        unit: 'hộp',
        importPrice: 28000,
        sellPrice: 38000,
        discountPrice: null,
        expiryDate: addDays(25),
        stockQuantity: 25,
        minStockThreshold: 5,
    },
    {
        code: 'SP0015',
        name: 'Giấy vệ sinh Bless You 10 cuộn',
        category: 'Hóa phẩm gia dụng',
        unit: 'lốc',
        importPrice: 45000,
        sellPrice: 60000,
        discountPrice: null,
        expiryDate: null,
        stockQuantity: 60,
        minStockThreshold: 10,
    },
    {
        code: 'SP0016',
        name: 'Nước rửa chén Sunlight chai 750g',
        category: 'Hóa phẩm gia dụng',
        unit: 'chai',
        importPrice: 25000,
        sellPrice: 34000,
        discountPrice: 30000,
        expiryDate: null,
        stockQuantity: 40,
        minStockThreshold: 10,
    },
    {
        code: 'SP0017',
        name: 'Bàn chải đánh răng Colgate (1 cây)',
        category: 'Hóa phẩm gia dụng',
        unit: 'cây',
        importPrice: 8000,
        sellPrice: 12000,
        discountPrice: null,
        expiryDate: null,
        stockQuantity: 100,
        minStockThreshold: 20,
    },
    {
        code: 'SP0018',
        name: 'Khẩu trang y tế 3 lớp hộp 50 cái',
        category: 'Y tế & sức khỏe',
        unit: 'hộp',
        importPrice: 35000,
        sellPrice: 45000,
        discountPrice: null,
        expiryDate: addDays(700),
        stockQuantity: 50,
        minStockThreshold: 10,
    },
    {
        code: 'SP0019',
        name: 'Pin AA Energizer (vỉ 4 viên)',
        category: 'Đồ dùng khác',
        unit: 'vỉ',
        importPrice: 20000,
        sellPrice: 28000,
        discountPrice: null,
        expiryDate: null,
        stockQuantity: 30,
        minStockThreshold: 5,
    },
    {
        code: 'SP0020',
        name: 'Bia Tiger lon 330ml',
        category: 'Đồ uống có cồn',
        unit: 'lon',
        importPrice: 12000,
        sellPrice: 17000,
        discountPrice: null,
        expiryDate: addDays(240),
        stockQuantity: 96,
        minStockThreshold: 24,
    },
];

async function seedProducts() {
    for (const p of products) {
        try {
            // Dùng mã SP làm document ID để tránh trùng lặp khi chạy lại
            await db.collection('products').doc(p.code).set({
                ...p,
                createdAt: new Date().toISOString(),
                updatedAt: new Date().toISOString(),
            });

            console.log(`✅ Tạo sản phẩm thành công:`, p.code, '-', p.name);
        } catch (err) {
            console.error(`❌ Lỗi tạo sản phẩm ${p.code}:`, err.message);
        }
    }
    process.exit(0);
}

seedProducts();